platform :ios, '9.0'

target 'AnnieParts' do
  use_frameworks!

  # Pods for AnnieParts
  pod 'Alamofire'
  pod 'SwiftyJSON'


  pod 'Kingfisher'
  pod 'SKPhotoBrowser'
  pod 'Auk'
  pod 'moa'

  pod 'SwiftyUtils'

  pod 'Presentr'
  pod 'SwipeCellKit'
end
