platform :ios, '9.0'

target 'AnnieParts' do
  use_frameworks!

  # Pods for AnnieParts
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SKPhotoBrowser'
  pod 'moa'
  pod 'Auk'
  pod 'PagingMenuController'
  pod 'SwiftyJSON'
end
